#!/bin/sh
echo "[?] What is the name of new github repo?"
read pname
if [ $pname ! = "" ]; then
    echo "[?] What is your github username?"
    read gname
    if [ $gname != "" ];
        curl -u $gname https://api.github.com/user/repos -d '{"name":"'$pname'"}'
        echo "git remote add origin https://github.com/$gname/$pname.git"
        echo "git push -u origin master"
    fi
fi
